feat(index): Add blog.ght1pc9kc.fr and remove breaking links
brownbaglunch/BrownBagLunch pull request #356
Opened 2023-11-28 12:24 UTC by Marthym

2023-11-29 20:48 UTC, linsolas requested changes

2023-11-29 20:48 UTC, linsolas commented on index.html
> -                                <li><i class="icon-hand-right"></i> <a href="http://linsolas.github.com/blog/2013/02/09/lancez-vous-dans-les-brown-bag-lunches/">Lancez-vous dans les Brown Bag Lunches
Merci, mon blog était HS - enfin, le bon lien à mettre est celui-ci : 

https://linsolas.github.io/blog/2013/02/09/lancez-vous-dans-les-brown-bag-lunches/

2023-11-30 08:58 UTC, Marthym commented on index.html
> -                                <li><i class="icon-hand-right"></i> <a href="http://linsolas.github.com/blog/2013/02/09/lancez-vous-dans-les-brown-bag-lunches/">Lancez-vous dans les Brown Bag Lunches
C'est fait

2023-11-30 10:47 UTC, dadoonet reviewed
Tiens. On pourrait en profiter pour ajouter mon article sur les BBLS: https://www.elastic.co/blog/free-lunch-for-open-source-engineers

2023-11-30 11:09 UTC, Marthym commented
> Tiens. On pourrait en profiter pour ajouter mon article sur les BBLS: https://www.elastic.co/blog/free-lunch-for-open-source-engineers

Surement oui, peut être qu'un PR dédié serait peut être plus approprié. Dans la mesure où je ne sais pas si l'idée de la liste est d'ajouter des liens anglais ou pas. Je suppose que c'est un autre sujet.

2023-11-30 11:10 UTC, dadoonet commented
Ouais. Je vais attendre que celle là soit fusionnée :)

2023-12-01 17:18 UTC, merged